### ISSUE TITLE
Share generated image to messengers/file storages

### ISSUE THREAD

**Issue by AlexeyKolosov** [EntyR/RandomNumberDB#25]
By pressing the button user should see system bottom sheet with apps, which are ready to acquire this picture. Then by selecting an app, for example Notes or GoogleDrive, this picture should be shared to this selected app. 

add button 
![image](https://user-images.githubusercontent.com/48712070/158586431-6747420b-c68e-4621-b29d-4f0fd30d81fd.png)
Shared image:
![image](https://user-images.githubusercontent.com/48712070/158585125-4b407d19-09b3-4c15-acee-f28a1ff87123.png)

**Comment by EntyR** [comment]
done, but might be better option, implemented it by saving layout picture via mediastore. retrieving its uri and putting it into intent
